### ISSUE TITLE
blog-image

### ISSUE THREAD

**Issue by pablogsal** [willianjusten/will-jekyll-template#10]
I'm wondering what is the use of the /assets/img/blog-image.png . I mean, it's some sort of image to put in the header of every post? I'm looking at the source code but I do not get what is the use of the image. Looking at your blog (http://willianjusten.com.br/) does not tell me nothing more as I do not see personalised images in the headers /post.

Can you tell a detailed description and uses of this image?

It is possible to put images in the header of the homepage or blog post pages?

Thank you!

**Comment by willianjusten** [comment]
Hi @pablogsal, the blog-image.png is used on [facebook meta tags here](https://github.com/willianjusten/will-jekyll-template/blob/gh-pages/_includes/head.html#L29), I use that to define my Dummy Image when I didn't set a new image on my post.

To change the header of home you just need to set a `background-image` [here].(https://github.com/willianjusten/will-jekyll-template/blob/gh-pages/src/styl/_header.styl#L6)

Thanks and sorry for my bad english...
