### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by pablogsal** [willianjusten/will-jekyll-template#11]
About changing background image:

$bg
        background-image './../img/blog-image.png'
    background main
    height 100%
    .content
        width 95%
        align(both)
        text-align center

does not seem to work. What i am doing wrong?

Thank you so much for your wonderful work :)

**Comment by willianjusten** [comment]
In `CSS` when you define two types of same property, the last will prevail.

When you define 

```
background-image './../img/blog-image.png'
background main
```

The last `background main` is the used. Try to remove `background main` line.

**Comment by pablogsal** [comment]
Sadly, it does not seem to work, the home webpage looks the same and no
image appears, only the blue background.

Some ideas?

Thank you again!

**Comment by willianjusten** [comment]
Your syntax for `background-image` is wrong.

You are using => `background-image './../img/blog-image.png'` 
The correct => `background-image 'url(./../img/blog-image.png)'`

**Comment by pablogsal** [comment]
I'm sorry for the bothering, but that does not work also.

**Comment by willianjusten** [comment]
You are compiling your styl?

**Comment by willianjusten** [comment]
Using `gulp` tasks?

**Comment by pablogsal** [comment]
Yup, i will try to rebuild the NodeJS and the gulp to check if something is wrong.

Thank you and sorry for the bothering.

**Comment by willianjusten** [comment]
Follow these steps:

1) Change the stylus.
2) Run `gulp stylus`.
3) Run the whole project with `gulp`.

**Comment by willianjusten** [comment]
If you look to [your css file](https://github.com/pablogsal/pablogsal.github.io/blob/master/assets/css/main.css), you don't have your background image. This happens because you forgot to compile and push your new code. Take a look to your terminal responses..

**Comment by pablogsal** [comment]
Yes, yes, I'm doing the tests in local with jekyll serve, that's the reson that is not changed in github.

**Comment by pablogsal** [comment]
Sorry for the inconvenience and thank you!

**Comment by pablogsal** [comment]
Perfect, now it works! 

Thank you so much and sorry for the bothering!

**Comment by willianjusten** [comment]
Great! =)
