### ISSUE TITLE
Change directory from "will-jekyll-template" to "/" breaks site

### ISSUE THREAD

**Issue by kfallah** [willianjusten/will-jekyll-template#14]
In the config whenever I change the directory of the site from "will-jekyll-template" to just "/", it also ends up breaking all the styling. Also, in the build tutorial it advises to install nodejs, do npm install, and then run gulp. How is gulp meant to be run? Anything I try returns gulp not being recognized for some reason... Thanks!

**Comment by kfallah** [comment]
Ignore the gulp bit, figured that out. The first part still stands though

**Comment by willianjusten** [comment]
Hey @kfallah, if you don't want to use a subfolder like `/blog` or anything else, just let the config with empty value, like: `baseurl: ""`.

This url is used in another parts of layout to call our assets.

**Comment by kfallah** [comment]
@willianjusten for some reason when I leave baseurl empty, everything falls apart. When I change it to anything else it works fine, but it doesn't for just  `basurl: "". I'll try and get a picture to show what I mean.

**Comment by willianjusten** [comment]
Hum...weird...
I use this template on my [own blog](https://github.com/willianjusten/willianjusten.github.io) and everything works like a charm..

**Comment by kfallah** [comment]
http://i.imgur.com/gSvh7Bl.jpg

**Comment by kfallah** [comment]
Is there anything besides `baseurl` I should be changing perhaps?

**Comment by willianjusten** [comment]
Please, show me the console.log errors or some link to access...

**Comment by kfallah** [comment]
http://kfallah.me:3000/ here is a link to the site, i'll check for errors

**Comment by kfallah** [comment]
No errors in the console nor by npm... Is there anywhere else I should look?

**Comment by willianjusten** [comment]
I can't open your link...Are you sure this url is open?
Take a look to your network tab on your browser and look for 404 errors...

**Comment by kfallah** [comment]
I tested it on a couple devices and its working... :worried: It's on port 3000 of the site though, not port 80.

Try this maybe? It's on port 4000 now:
http://kfallah.me:4000/

**Comment by willianjusten** [comment]
Maybe it's your network configuration?

**Comment by kfallah** [comment]
The network configuration on the hosting server? What would be wrong with it so that you couldn't connect? I'm connecting from an external network myself.

**Comment by willianjusten** [comment]
![screen shot 2015-09-30 at 3 31 41 pm](https://cloud.githubusercontent.com/assets/3991845/10202681/6771a76c-6788-11e5-8152-3ad3ead92704.png)

**Comment by kfallah** [comment]
Use port 4000, i'm running it through `jekyll serve` now.
http://kfallah.me:4000/

**Comment by willianjusten** [comment]
I tried with 4000 also and not happens...

Please, show me your network tab...

**Comment by kfallah** [comment]
This network tab?

![screenshot](https://cloud.githubusercontent.com/assets/9440350/10202826/be066a8e-6780-11e5-9f17-3e73c985ad3a.jpg)

**Comment by kfallah** [comment]
So when I actually built it, it works? It only isn't working when I serve it through jekyll. Very weird, but that works for me. Thanks for the help!

**Comment by willianjusten** [comment]
Hum...yeah, you have to compile your files first...

**Comment by kfallah** [comment]
Sorry for that misunderstanding :smile:

**Comment by willianjusten** [comment]
No problem =)
