### ISSUE TITLE
Code blocks and fenced code blocks

### ISSUE THREAD

**Issue by vsential** [willianjusten/will-jekyll-template#17]
I might be missing something but I can't seem to get the syntax highlighting working properly.  I get the gray background code block but the syntax is not being highlighted.  Any help would be appreciated.  Thanks!

**Comment by willianjusten** [comment]
Can you show me your snippet code?

**Comment by vsential** [comment]
Sure...it is some Powershell code and I have more but this is the first one I was moving over.  Here is the page that is not working: http://vsential.github.io/2010/08/06/scripts-export-vm-name-and-vmdk-size/

And the code snippet is:

<pre>
{% highlight powershell %}
# PowerCLI Script to gather VM Information (Name, VMDK Size)
# Scripted by James Bowling <jbowling @vsential.com>
#
#Global Functions
function Get-VmSize($vm)
{
#Initialize variables
$VmDirs =@()
$VmSize = 0
$searchSpec = New-Object VMware.Vim.HostDatastoreBrowserSearchSpec
$searchSpec.details = New-Object VMware.Vim.FileQueryFlags
$searchSpec.details.fileSize = $TRUE
Get-View -VIObject $vm | % {
#Create an array with the vm's directories
$VmDirs += $_.Config.Files.VmPathName.split("/")[0]
$VmDirs += $_.Config.Files.SnapshotDirectory.split("/")[0]
$VmDirs += $_.Config.Files.SuspendDirectory.split("/")[0]
$VmDirs += $_.Config.Files.LogDirectory.split("/")[0]
#Add directories of the vm's virtual disk files
foreach ($disk in $_.Layout.Disk) {
foreach ($diskfile in $disk.diskfile){
$VmDirs += $diskfile.split("/")[0]
}
}
#Only take unique array items
$VmDirs = $VmDirs | Sort | Get-Unique
foreach ($dir in $VmDirs){
$ds = Get-Datastore ($dir.split("[")[1]).split("]")[0]
$dsb = Get-View (($ds | get-view).Browser)
$taskMoRef  = $dsb.SearchDatastoreSubFolders_Task($dir,$searchSpec)
$task = Get-View $taskMoRef
while($task.Info.State -eq "running" -or $task.Info.State -eq "queued"){$task = Get-View $taskMoRef }
foreach ($result in $task.Info.Result){
foreach ($file in $result.File){
$VmSize += $file.FileSize
}
}
}
}
return $VmSize
}
# Variables
$VIServer = "VISERVER"
$username = "changeme"
$password = "supersecure"
$Folder = "C:"
# Connect to VIServer
Connect-VIServer $VIServer -user $username -Password $password
#Initialise Array
$Report = @()
# Gather VM Information
$AllVMs = Get-View -ViewType VirtualMachine | Where {-not $_.Config.Template}
$SortedVMs = $AllVMs | Select *, @{N="NumDisks";E={@($_.Guest.Disk.Length)}} | Sort-Object -Descending NumDisks
ForEach ($VM in $SortedVMs){
$Details = New-object PSObject
$Details | Add-Member -Name Name -Value $VM.name -Membertype NoteProperty
$DiskNum = 0
Foreach ($disk in $VM.Guest.Disk){
$Details | Add-Member -Name "Disk$($DiskNum)Capacity(GB)" -MemberType NoteProperty -Value ([math]::Round($disk.Capacity/ 1024MB))
$DiskNum++
}
$Report += $Details
}
$Report | Export-Csv "C:VMDiskSize.csv"
# Disconnect from VIServer
Disconnect-VIServer $VIServer -Confirm:$False
{% endhighlight %}
</pre>

**Comment by willianjusten** [comment]
Hi @vsential, it seems your sintax isn't iddentified by my highlight css...
I'm planning to change that soon, if you can wait...

**Comment by vsential** [comment]
I can definitely wait as I have not moved this into production just yet.  I still have some touching up to do and some other changes that I need to make as well.  I appreciate the quick help on this!

**Comment by willianjusten** [comment]
Hi, I've changed to use Monokai Style, it looks like Sublime Text default colors. Take a look =D

**Comment by vsential** [comment]
Looks good.  Thanks for the work and quick turnaround!

**Comment by willianjusten** [comment]
I'm happy that you liked it. =D

Waiting for your PR changing the script to pass drafts to posts.
