### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by Joshfindit** [willianjusten/will-jekyll-template#2]
http://willianjusten.com.br/will-jekyll-template/

Most links point to http://willianjusten.com.br/ (such as http://willianjusten.com.br/welcome-to-jekyll/ )
The menu links point to localhost:3000

**Comment by ericmconnelly** [comment]
fix it by deleting localhost:3000 in _config.yml

**Comment by willianjusten** [comment]
You have to change some informations in your `config.yml`, take a look [here](https://github.com/willianjusten/will-jekyll-template/blob/gh-pages/_config.yml#L3-L4) =)
