### ISSUE TITLE
xlink icons? 

### ISSUE THREAD

**Issue by HintikkaKimmo** [willianjusten/will-jekyll-template#21]
How do I change one social media icons on the landing page? 

I have figured that links are defined at header-default.html file so I can change the hyper link there. 

Icons are located at svg-icons.html if I get understand this correctly. Where is is this source coming from and how I add linkedin icon with same styling? 

I am looking to replace google+ with linkedin.

**Comment by willianjusten** [comment]
Hi @HintikkaKimmo , all you said is correct. I use SVG icons located on this file. Everything you have to do is put another svg icon there and add a link on header-default.

Take a look at this example:
- [Home](http://blog.devparana.org/)
- [SVG file modified](https://github.com/DeveloperParana/blog/blob/master/_includes/svg-icons.html)

**Comment by HintikkaKimmo** [comment]
Thanks got it. For what ever reason my Linkedin SVG does not render correctly, but after testing with Facebook icon I am sure its because the SVG itself. Should have tested first I raised this because I was thinking I missed some step after getting pretty weir result with my icons.
