### ISSUE TITLE
add disqus

### ISSUE THREAD

**Issue by ghost** [willianjusten/will-jekyll-template#22]
Hi, nice theme. How can I add Disqus comments? I actually added disqus_username in _config.yml. But it still not working. "We were unable to load Disqus. If you are a moderator please see our troubleshooting guide." 
## Please, can you help me? 

Wish you every success

**Comment by Adejair** [comment]
You created admin page on disqus? [if not](https://disqus.com/admin/create/)

After create your page admin on disq you have one link (e.g _adejair.disqus.com_), get your username(_before_ .disqus.com) and put in file `_config.yml` on line `disqus_username:` 

Finish, you configured disqus on your awesome site :checkered_flag:

**Comment by willianjusten** [comment]
@Adejair said everything you need to do. Just create an account on [disqus](https://disqus.com/admin/create/) and place your username on [_config.yml - Line 14](https://github.com/willianjusten/will-jekyll-template/blob/gh-pages/_config.yml#L14).
