### ISSUE TITLE
question about 'comment section'

### ISSUE THREAD

**Issue by jihobak** [willianjusten/will-jekyll-template#29]
first, I would like to say, thank you for your help about Jekyll blog.

 Here is my problem, I can't not find my error in 'comment section'
 my blog is http://jihobak.github.io/blog/

![image](https://cloud.githubusercontent.com/assets/10293523/15420602/ad26312e-1ea8-11e6-8c62-fbfa003f617c.png)

after clicking troubleshooting, there's no change..
where should I check for this issue ? 

Thanks

**Comment by willianjusten** [comment]
Hi @jihobak, did you create an account on Disqus? It seems something is wrong with your authentication...

**Comment by jihobak** [comment]
Thanks for your answer, It was my fault and I made a new disqus ID to handle this problem.

**Comment by willianjusten** [comment]
Nice =D
