### ISSUE TITLE
(Question)about creating post

### ISSUE THREAD

**Issue by jihobak** [willianjusten/will-jekyll-template#30]
I made a post in folder '_post' (set layout, title, date...) but when I deploy to my github pages, there's no post on site( just exist in '_post' folder. In addition, there's no any additional folder like 'how to use', 'welcome-to-jekyll' in '_site' folder after gulp...unlikely other post.)

In this case, Where should I check..? 

Thanks!!

**Comment by willianjusten** [comment]
You just need to run `./initpost.sh -c Post Title` and your post will be created on `_posts` folder. The folder is in plural => `_posts`.  

Maybe you are doing something wrong at your configuration, take a look at your terminal in search for some error.

**Comment by jihobak** [comment]
@willianjusten Thanks!!

**Comment by willianjusten** [comment]
=D
