### ISSUE TITLE
suggest about simpleJekyllSearch.js

### ISSUE THREAD

**Issue by jihobak** [willianjusten/will-jekyll-template#31]
![image](https://cloud.githubusercontent.com/assets/10293523/15527167/057229dc-2273-11e6-9608-01c3ee8b1dc7.png)
If there is 'baseurl' like '/blog'

I think there should be some change in 'jsonFile' in file simpleJekyllSearch.js like below
![image](https://cloud.githubusercontent.com/assets/10293523/15527196/465b426c-2273-11e6-9691-000512b4c52b.png)

after gulp, I can find some change in main.js located in 'assets/js'
So, we can use searching in our own gh-page

**Comment by willianjusten** [comment]
Sorry @jihobak , but I can't understand, what you suggest to do?

**Comment by jihobak** [comment]
@willianjusten
In default, jsonFile : '/search.json' 
so If I made blog in "jihobak.github.com/blog". the search function in the blog doensn't work.
For example, I made a new post which title 'sample posting'. If i search 'sample posting', 
thers's no 'sample posting' in result.

Therefore, I mean, If user add 'baseurl"(like /blog), there should be change in jsonFile(like '/blog/search.json' not '/search.json')

Sorry, I'm not fluently at English
Thanks for your answering

**Comment by willianjusten** [comment]
Oh, yeah, you are right....But I can't figure out how to change this url inside the javascript file...I'll think about that...

**Comment by jihobak** [comment]
or some guide about this point in README.md is very helpful. Actually this blog is already awesome
Thanks!

**Comment by willianjusten** [comment]
Oh good idea, I'll update the README with this disclaimer. Thanks =)

**Comment by jihobak** [comment]
what if I want to pull request to here, Is it possible?
If it is okay, Is there any specific rules that you think contributors should follow

**Comment by willianjusten** [comment]
Pull is always welcome =)

You just need to do what you want and send me with some explanation about you did.

**Comment by jihobak** [comment]
Okay thanks!! :)
