### ISSUE TITLE
Question for making new theme set

### ISSUE THREAD

**Issue by minibrary** [willianjusten/will-jekyll-template#33]
Hi, Willian Justen,

I just began to test your gorgeous jekyll theme.
I just wondered how come adding new theme with main-class does not applied at github pages?

File link as below
https://github.com/minibrary/en.blog/blob/gh-pages/src/styl/_theme-colors.styl

Created post-linux and post-win with specific color.

Even applying new post, it is not effective.

Do you know the reason of this?

Best Regards,
- Minibrary -

**Comment by minibrary** [comment]
Hi buddy, I found answer from closed issue, need to compile again by gulp.
Sorry for bothering you let me test it.

**Comment by willianjusten** [comment]
Hey @minibrary, the correct repo is [cards-jekyll-template](https://github.com/willianjusten/cards-jekyll-template) also =)

This repo here is from my blue template.
