### ISSUE TITLE
_config.yml gplus_username

### ISSUE THREAD

**Issue by bebo-dot-dev** [willianjusten/will-jekyll-template#36]
Where you configure a gplus_username - is this the long number type Id for my google+ account? When I insert that I end up with a broken link to google+ that looks like this: https://plus.google.com/+108205719135497472486/posts - it seems to be the + just before the Id that's the problem. Is this me doing something wrong or a bug do you think?
Thanks
Joe

**Comment by willianjusten** [comment]
I put at this [line](https://github.com/willianjusten/will-jekyll-template/blob/gh-pages/_includes/head.html#L10), so you just need to past your Id.

**Comment by willianjusten** [comment]
Oh...my mistake, this plus sign wasn't to be there..
