### ISSUE TITLE
google fonts and SSL

### ISSUE THREAD

**Issue by bebo-dot-dev** [willianjusten/will-jekyll-template#40]
Hi there's a mixed content problem with google fonts rendering over SSL. You can see this problem with your hosted sample: 

> Mixed Content: The page at 'https://willianjusten.com.br/will-jekyll-template/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/opensans/v10/DXI1ORHCpsQm3Vp6mXoaTRampu5_7CjHW5spxoeN3Vs.woff2'. This request has been blocked; the content must be served over HTTPS.

It's caused by https://github.com/willianjusten/will-jekyll-template/blob/1a3dc03a47d95bf9db10314d0e038d8b456183c8/src/styl/_typo.styl#L8 + https://github.com/willianjusten/will-jekyll-template/blob/1a3dc03a47d95bf9db10314d0e038d8b456183c8/src/styl/_typo.styl#L15 and the css generated from this.

I've fixed it myself by editing these urls in my fork directly to https://fonts.gstatic.com but I can't really submit this as a pull request because I don't know if this is the right fix / if this is how you'd like it fixed.

**Comment by willianjusten** [comment]
I've changed my urls to https these days...So, some places are breaking because of this... 

Fixed on [d9a70d](https://github.com/willianjusten/will-jekyll-template/commit/d9a70d0fee617efc79b445b9d1bbea862ba14672)

**Comment by bebo-dot-dev** [comment]
yip this would be a problem anywhere this template is served over ssl/tls
