### ISSUE TITLE
Out of the box - broken

### ISSUE THREAD

**Issue by noxidsoft** [willianjusten/will-jekyll-template#46]
C:\xampp\htdocs\dev\9.0.0>gulp
[11:09:29] Using gulpfile C:\xampp\htdocs\dev\9.0.0\gulpfile.js
[11:09:29] Starting 'js'...
[11:09:29] Starting 'stylus'...
[11:09:29] Finished 'stylus' after 4.71 ms
[11:09:29] Starting 'jekyll-build'...
[11:09:29] Starting 'watch'...
[11:09:29] Finished 'watch' after 115 ms
[11:09:29] Plumber found unhandled error:
 Error in plugin 'gulp-stylus'
Message:
    C:\xampp\htdocs\dev\9.0.0\src\styl\main.styl:22:9
   18|     And of course, look in node_modules for axis-css and jeet
   19| */
   20|
   21| @import "kouto-swiss"
   22| @import "jeet"
---------------^
   23| normalize()
   24| @import "_variables"
   25| @import "_typo"

failed to locate @import file jeet.styl

Details:
    lineno: 22
    column: 9
    filename: C:\xampp\htdocs\dev\9.0.0\src\styl\main.styl
    stylusStack:
    input: /\*  Syntax Quick Reference for Jeet
    --------------------------
    column(ratios = 1, offset = 0, cycle = 0, uncycle = 0, gutter = jeet.gutter)
    span(ratio = 1, offset = 0)
    shift(ratios = 0, col_or_span = column, gutter = jeet.gutter)
    unshift()
    edit()
    center(max_width = 1410px, pad = 0)
    stack(pad = 0, align = false)
    unstack()
    align(direction = both)
    cf()

```
For more info see:
    Kouto Swiss Doc: http://kouto-swiss.io/
    Jeet Doc: http://jeet.gs

And of course, look in node_modules for axis-css and jeet
```

*/

@import "kouto-swiss"
@import "jeet"
normalize()
@import "_variables"
@import "_typo"
@import "_animations"
@import "_icons"
@import "_menu"
@import "_search"
@import "_elements"
@import "_header"
@import "_home"
@import "_post"
@import "_hightlight"
@import "_author"
@import "_footer"
[11:09:30] Finished 'js' after 1.29 s
Configuration file: C:/xampp/htdocs/dev/9.0.0/_config.yml
            Source: C:/xampp/htdocs/dev/9.0.0
       Destination: C:/xampp/htdocs/dev/9.0.0/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.617 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
[11:09:31] Finished 'jekyll-build' after 2.39 s
[11:09:31] Starting 'browser-sync'...
[11:09:31] Finished 'browser-sync' after 130 ms
[11:09:31] Starting 'default'...
[11:09:31] Finished 'default' after 2.78 μs
[BS] Local URL: http://localhost:3000
[BS] External URL: http://192.168.56.1:3000
[BS] Serving files from: _site
Terminate batch job (Y/N)?
^C
C:\xampp\htdocs\dev\9.0.0>

![image](https://cloud.githubusercontent.com/assets/729135/16935281/61534e1c-4da1-11e6-8035-6d8640100ccf.png)

**Comment by willianjusten** [comment]
Hey @noxidsoft, all you need to do is install `jeet` again, they have changed their version and broke here.. I updated all versions also if you don't know how to update...

**Comment by felippepuhle** [comment]
Hi, still the same here, even with jeet's new version... Would you help me? =]

**Comment by willianjusten** [comment]
@lippep, try to install `npm install jeet@6.1.2` please. I'm going to fix those dependencies issues later...I'm very busy right now =/

**Comment by noxidsoft** [comment]
No, I'm not deprecating. A workaround might be to just change the import of Jeet 6.1.4 from this:

```
@import "jeet"
```

to this:

```
@import "jeet/_jeet.styl"
```

I tested rather, and it works fine. Jeet has problems though with center() of which they are aware.

**Comment by noxidsoft** [comment]
@lippep you can find the file to change in src/styl/main.styl line 22 (approx).

Change it to the following:

```
@import "jeet/_jeet.styl"
```

Then re-run gulp. Let me know how you get on, I was able to get things working in the end, hope you do too.

**Comment by willianjusten** [comment]
@noxidsoft, I solved this same problem just changing to jeet@6.1.2 with another person...
I'll test everything this weekend and create a new release of this template, fixing everything we need to.

**Comment by felippepuhle** [comment]
Thanks guys! I solved this changing jeet to 6.1.2(without ^) on package.json.
Sorry for the incovenience, I'm new with stylus... Don't worry with updates @willianjusten, I'm very busy right now too, and don't have too much time to spend with this project... 

Thanks again!

**Comment by felippepuhle** [comment]
I'm seeing another problems with the project in production (http://felippepuhle.github.io). Can I fork, fix and make a PR?
- Jeet's version on package
- Assets url

**Comment by willianjusten** [comment]
@felippepuhle, you have to change your baseurl on your _config.yml, removing "will-jekyll-template". 

It's the 4th step in the [Basic Setup](https://github.com/willianjusten/will-jekyll-template#basic-setup).

And yeah, everyone here can send me a PR with fixes, it would be great.

**Comment by felippepuhle** [comment]
I've already done that, the error remains. I'll take a look later, thanks!

**Comment by willianjusten** [comment]
Well...I don't know if you are using some aggressive cache or anything else, but it keeps using "will-jekyll-template" on every request...

![screen shot 2016-08-19 at 12 16 16 pm](https://cloud.githubusercontent.com/assets/3991845/17814537/c79480d8-6606-11e6-9a06-2abc224a5dfc.png)

**Comment by felippepuhle** [comment]
Yeah, I see that too! But don't worry, I'll take a look tonight... Probably I'm doing something wrong... Thanks for your time!

**Comment by willianjusten** [comment]
Ok, let me know if you need some help.
