### ISSUE TITLE
gulp issue and thumbnail 

### ISSUE THREAD

**Issue by imsrgadich** [willianjusten/will-jekyll-template#48]
Hi, when I run **gulp** it gives me following error.

Screen shot of the error:

![screenshot from 2016-12-19 22-23-13](https://cloud.githubusercontent.com/assets/16464365/21328724/f3e850aa-c63d-11e6-8464-74cedf1d4fa0.png)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Issue with the thumbnail when ever I share my website, it uses the following image in the url as a thumbnail. How do I remove it?

https://external-amt2-1.xx.fbcdn.net/safe_image.php?d=AQDnZS1j81s_7Q_R&w=476&h=249&url=https%3A%2F%2Fimsrgadich.github.io%2Fassets%2Fimg%2Fblog-image.png&cfs=1&upscale=1&_nc_hash=AQBZhPUXtNdw8BFx

![screenshot from 2016-12-19 22-59-53](https://cloud.githubusercontent.com/assets/16464365/21328949/ed3e5230-c63e-11e6-965c-fff6c2d158ed.png)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Can you please help me with these issues?

Thanks!

**Comment by willianjusten** [comment]
Hey, sorry for this loooong delay...
Just answering in case that another one needs in the future.

The error in the gulp means that you don't have `jekyll` installed in your machine, so you should install and then run again.

And to change the thumbnail is easy. I have this [line](https://github.com/willianjusten/will-jekyll-template/blob/gh-pages/_includes/head.html#L29) when I add this image `/assets/img/blog-image.png`, you have 2 ways to change this:

- change the url to another image
- overwrite my image to yours

I hope it helps.

**Comment by imsrgadich** [comment]
Thank you!
