### ISSUE TITLE
Search button doesn't work in Safari

### ISSUE THREAD

**Issue by joshfuggle** [willianjusten/will-jekyll-template#5]
Hello!

The search button doesn't appear to be work in Safari?

(I am running safari version 8.0.8)

Tested, and it works fine in Chrome.

**Comment by willianjusten** [comment]
Hum, iOS Safari or Mac? And what happens?

**Comment by willianjusten** [comment]
Hi, so many thanks for this feedback =)
The problem was on `transform` property. Safari uses `-webkit-` prefix yet, so I need to pass this property.

I solved this using a new `active` class on `search-wrapper` giving correct properties of `transform`.
