### ISSUE TITLE
Modify index.html post description truncatewords to truncate to better support Non-Lation languages

### ISSUE THREAD

**Issue by shiyuge** [willianjusten/will-jekyll-template#53]
Currently codes in index.html there is truncatewords to shorten post description, which works fine.
```
 <p class="description">
  {{ post.content | strip_html | truncatewords:40 }}
 <a href="{{ post.url | prepend: site.baseurl }}" class="link">Read more about {{post.title}}</a>
 </p>
```
However, in non-Latin languages, problems arise. For example in Chinese, a sentence is made of a list of characters **without white spaces**, which is recognized as "one word" by the program.
I suggest change truncatewords to truncate to better support Chinese Language, it works fine for me.

**Comment by willianjusten** [comment]
I got your point, but for latin it's better to keep with `truncatewords` since it has more meaning to us than cut the word in a middle =x

But thanks for pointing out.
