### ISSUE TITLE
Search function does not work

### ISSUE THREAD

**Issue by vuncrychen** [willianjusten/will-jekyll-template#71]
Hi, I tried to use the search function on the demo site, but it doesn't seem to work. 
Does anyone know what's going on?

Regards.

**Comment by willianjusten** [comment]
Oh actually this is happening because the search is trying to run under a wrong url, because it's using only `/search.json` instead of the full url.

https://github.com/willianjusten/will-jekyll-template/blob/gh-pages/src/js/simpleJekyllSearch.js#L4

**Comment by willianjusten** [comment]
I just fixed this issue and created a step inside the Readme, besides that, I also added a `not maintained` flag, since this is a very old code and I don't use or mantain anymore...
